### ISSUE TITLE
xapian_rs Operator type is not visible on exported enums

### ISSUE THREAD

**Issue by OmentaElvis** [torrancew/xapian-rs#1]
I need to apply Filter operator on my xapian Query but it seems that the xapian_rs::Operator enum is not available for use externally. Some functions like

pub fn [combine](https://docs.rs/xapian-rs/latest/xapian_rs/struct.Query.html#method.combine)(op: Operator, a: impl [AsRef](https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html)<Query>, b: impl [AsRef](https://doc.rust-lang.org/nightly/core/convert/trait.AsRef.html)<Query>) -> Self

do require the Operator enum but it is not accessible.

**Comment by torrancew** [comment]
@OmentaElvis I'll cut a release soon and fix that for you! sorry!

**Comment by torrancew** [comment]
@OmentaElvis Sorry I didn't see this earlier, but this is released in `v0.2.1`.

My own usage of this library is fairly trivial so far, and mostly uses the `QueryParser` -- but if you have more use cases that aren't covered let me know and I'll try to add them!
